packages:
  - app/client
  - app/server
  - app/shared
  - app/launcher
  - apps/jaraoke-studio/client
  - apps/jaraoke-studio/server

allowBuilds:
  core-js: false
  esbuild: true

catalog:
  "@types/node": "^24.7.0"
  typescript: "~5.9.3"
