packages:
  - apps/jaraoke/client
  - apps/jaraoke/server
  - apps/jaraoke-studio/client
  - apps/jaraoke-studio/server
  - packages/launcher
  - packages/shared

allowBuilds:
  core-js: false
  esbuild: true

catalog:
  "@types/node": "^24.7.0"
  typescript: "~5.9.3"
