import type { AssLine, LyricBuilderAssOptions } from 'jaraoke-shared/types';

const DEFAULT_SCREEN = {
  width: 1280,
  height: 720,
};

const padTiming = (value: number) => value.toString().padStart(2, '0');

export const createAssTimingFormatter = (unitsPerSecond: number) => {
  const unitsPerMinute = unitsPerSecond * 60;
  const unitsPerCentisecond = unitsPerSecond / 100;

  return (value: number) => {
    const minutes = Math.floor(value / unitsPerMinute);
    const seconds = Math.floor(
      (value - minutes * unitsPerMinute) / unitsPerSecond,
    );
    const remainingUnits =
      value - (minutes * unitsPerMinute + seconds * unitsPerSecond);
    const centiseconds = Math.floor(remainingUnits / unitsPerCentisecond);

    return `${padTiming(minutes)}:${padTiming(seconds)}.${padTiming(centiseconds)}`;
  };
};

interface ConstructCountdownOptions {
  firstTiming: number;
  startingNumber?: number;
  paddingTiming?: number;
  unitsPerSecond: number;
}

export const constructCountdown = ({
  firstTiming,
  startingNumber = 3,
  paddingTiming = 100,
  unitsPerSecond,
}: ConstructCountdownOptions): AssLine[] => {
  return Array.from({ length: startingNumber }, (_, index) => {
    const number = startingNumber - index;
    const countdownUnits = number * unitsPerSecond;

    return {
      start: firstTiming - countdownUnits - unitsPerSecond - paddingTiming,
      end: firstTiming - countdownUnits - paddingTiming,
      lyric: `{\\fad(300,300)}${number}`,
      style: 'Countdown',
    };
  });
};

interface AssLayoutOptions {
  fontSize: number;
  maxLinesOnScreen: number;
  screen?: LyricBuilderAssOptions['screen'];
}

interface ResolvedAssFontSizes {
  lyrics: number;
  subtitle: number;
}

export const resolveAssFontSizes = (
  fontSize?: LyricBuilderAssOptions['fontSize'],
): ResolvedAssFontSizes => {
  const lyrics = fontSize?.lyrics ?? 48;
  const subtitle =
    fontSize?.subtitle ?? Math.max(20, Math.round(lyrics * 0.55));

  return {
    lyrics,
    subtitle,
  };
};

export const createAssLayout = ({
  fontSize,
  maxLinesOnScreen,
  screen,
}: AssLayoutOptions) => {
  const { width, height } = screen || DEFAULT_SCREEN;
  const initialStartPos = height / maxLinesOnScreen;
  const positions = Array.from(
    { length: maxLinesOnScreen },
    (_, index) => initialStartPos + fontSize * index,
  );

  return {
    height,
    centerX: width / 2,
    positions,
  };
};

interface AssTemplateOptions {
  font: string;
  fontSize: number;
}

export const createAssTemplate = ({
  font,
  fontSize,
}: AssTemplateOptions) => `[Script Info]
; Script generated by Aegisub 3.4.2
; http://www.aegisub.org/
Title: Default Aegisub file
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: None
PlayResX: 1280
PlayResY: 720

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,${font},${fontSize},&H00FFFFFF,&H00FFFFFF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1
Style: Countdown,Arial Black,80,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,5,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
`;

interface DialogueLineOptions {
  start: number;
  end: number;
  lyric: string;
  style?: string;
  prefix?: string;
  formatTiming: (value: number) => string;
}

export const createDialogueLine = ({
  start,
  end,
  lyric,
  style = 'Default',
  prefix = '',
  formatTiming,
}: DialogueLineOptions) => {
  const startTiming = formatTiming(start);
  const endTiming = formatTiming(end);

  return `Dialogue: 0,0:${startTiming},0:${endTiming},${style},,0,0,0,,${prefix}${lyric}`;
};

interface DialogueWindow {
  start: number;
  end: number;
}

interface RenderAssChunkOptions<TLine extends { lyric: string }> {
  chunk: Array<TLine | undefined>;
  positions: number[];
  formatTiming: (value: number) => string;
  createPrefix: (args: { pos: number; isHighlighted: boolean }) => string;
  getWindow?: (
    line: TLine | undefined,
    index: number,
    chunk: Array<TLine | undefined>,
  ) => DialogueWindow | null;
  window?: DialogueWindow;
  highlightedIndex?: number;
}

export const renderAssChunk = <TLine extends { lyric: string }>({
  chunk,
  positions,
  formatTiming,
  createPrefix,
  getWindow,
  window,
  highlightedIndex,
}: RenderAssChunkOptions<TLine>) => {
  const renderedLines: string[] = [];

  for (let index = 0; index < chunk.length; index++) {
    const line = chunk[index];
    const pos = positions[index];
    const dialogueWindow = getWindow
      ? getWindow(line, index, chunk)
      : window || null;

    if (!dialogueWindow) {
      continue;
    }

    renderedLines.push(
      createDialogueLine({
        start: dialogueWindow.start,
        end: dialogueWindow.end,
        lyric: line?.lyric || '',
        prefix: createPrefix({
          pos,
          isHighlighted: index === highlightedIndex,
        }),
        formatTiming,
      }),
    );
  }

  return renderedLines;
};
